const fs = require('fs');

const filePath = 'c:/Users/pruth/Downloads/smiths/src/data/productsData.js';
let content = fs.readFileSync(filePath, 'utf8');

const rawProductsInsert = `  {
    id: 60,
    name: 'JC-KE-43',
    sku: 'JC-KE-43',
    slug: 'jc-ke-43',
    genre: 'EARRINGS',
    price: 849,
    originalPrice: 1799,
    reviewCount: 45,
    rating: 4.9,
    badCount: 1,
    image: '/images/products/jc-ke-43/hero-satin-pair.jpg',
    gallery: [
      '/images/products/jc-ke-43/hero-satin-pair.jpg',
      '/images/products/jc-ke-43/detail-hands-held.jpg',
      '/images/products/jc-ke-43/detail-satin-zoom.jpg',
      '/images/products/jc-ke-43/macro-camellia-detail.jpg',
    ],
  },
  {
    id: 59,
    name: 'JC-KE-2',
    sku: 'JC-KE-2',
    slug: 'jc-ke-2',
    genre: 'EARRINGS',
    price: 849,
    originalPrice: 1799,
    reviewCount: 53,
    rating: 4.9,
    badCount: 1,
    image: '/images/products/jc-ke-2/hero-studio-pair.jpg',
    gallery: [
      '/images/products/jc-ke-2/hero-studio-pair.jpg',
      '/images/products/jc-ke-2/detail-satin-pair.jpg',
      '/images/products/jc-ke-2/model-worn-profile.jpg',
      '/images/products/jc-ke-2/detail-hands-held.jpg',
      '/images/products/jc-ke-2/macro-wreath-detail.jpg',
    ],
  },
  {
    id: 58,
    name: 'JC-KE-34',
    sku: 'JC-KE-34',
    slug: 'jc-ke-34',
    genre: 'EARRINGS',
    price: 849,
    originalPrice: 1799,
    reviewCount: 47,
    rating: 4.9,
    badCount: 1,
    image: '/images/products/jc-ke-34/hero-satin-pair.jpg',
    gallery: [
      '/images/products/jc-ke-34/hero-satin-pair.jpg',
      '/images/products/jc-ke-34/model-worn-profile.jpg',
      '/images/products/jc-ke-34/model-studio-portrait.jpg',
      '/images/products/jc-ke-34/detail-card-held.jpg',
      '/images/products/jc-ke-34/macro-bow-detail.jpg',
    ],
  },
  {
    id: 57,
    name: 'JC-KE-33',
    sku: 'JC-KE-33',
    slug: 'jc-ke-33',
    genre: 'EARRINGS',
    price: 849,
    originalPrice: 1799,
    reviewCount: 51,
    rating: 4.9,
    badCount: 1,
    image: '/images/products/jc-ke-33/hero-studio-pair.jpg',
    gallery: [
      '/images/products/jc-ke-33/hero-studio-pair.jpg',
      '/images/products/jc-ke-33/model-worn-front.jpg',
      '/images/products/jc-ke-33/model-worn-side.jpg',
      '/images/products/jc-ke-33/detail-hands-held.jpg',
      '/images/products/jc-ke-33/macro-heart-detail.jpg',
    ],
  },
  {
    id: 56,
    name: 'JC-KE-32',
    sku: 'JC-KE-32',
    slug: 'jc-ke-32',
    genre: 'EARRINGS',
    price: 849,
    originalPrice: 1799,
    reviewCount: 48,
    rating: 4.9,
    badCount: 1,
    image: '/images/products/jc-ke-32/hero-satin-pair.jpg',
    gallery: [
      '/images/products/jc-ke-32/hero-satin-pair.jpg',
      '/images/products/jc-ke-32/model-worn-profile.jpg',
      '/images/products/jc-ke-32/detail-velvet-box.jpg',
      '/images/products/jc-ke-32/macro-butterfly-detail.jpg',
    ],
  },
  {
    id: 55,
    name: 'JC-KE-30',
    sku: 'JC-KE-30',
    slug: 'jc-ke-30',
    genre: 'EARRINGS',
    price: 849,
    originalPrice: 1799,
    reviewCount: 41,
    rating: 4.9,
    badCount: 1,
    image: '/images/products/jc-ke-30/hero-linen-pair.jpg',
    gallery: [
      '/images/products/jc-ke-30/hero-linen-pair.jpg',
      '/images/products/jc-ke-30/model-worn-profile.jpg',
      '/images/products/jc-ke-30/detail-satin-pair.jpg',
      '/images/products/jc-ke-30/detail-hands-held.jpg',
      '/images/products/jc-ke-30/macro-teardrop-detail.jpg',
    ],
  },
  {
    id: 54,
    name: 'JC-KE-29',
    sku: 'JC-KE-29',
    slug: 'jc-ke-29',
    genre: 'EARRINGS',
    price: 849,
    originalPrice: 1799,
    reviewCount: 56,
    rating: 4.95,
    badCount: 1,
    image: '/images/products/jc-ke-29/hero-plinth-pair.jpg',
    gallery: [
      '/images/products/jc-ke-29/hero-plinth-pair.jpg',
      '/images/products/jc-ke-29/model-worn-profile.jpg',
      '/images/products/jc-ke-29/detail-satin-pair.jpg',
      '/images/products/jc-ke-29/macro-camellia-detail.jpg',
    ],
  },
  {
    id: 53,
    name: 'JC-KE-28',
    sku: 'JC-KE-28',
    slug: 'jc-ke-28',
    genre: 'EARRINGS',
    price: 849,
    originalPrice: 1799,
    reviewCount: 43,
    rating: 4.9,
    badCount: 1,
    image: '/images/products/jc-ke-28/hero-satin-pair.jpg',
    gallery: [
      '/images/products/jc-ke-28/hero-satin-pair.jpg',
      '/images/products/jc-ke-28/detail-hand-worn.jpg',
      '/images/products/jc-ke-28/macro-cuff-detail.jpg',
    ],
  },
  {
    id: 52,
    name: 'JC-KE-26',
    sku: 'JC-KE-26',
    slug: 'jc-ke-26',
    genre: 'EARRINGS',
    price: 849,
    originalPrice: 1799,
    reviewCount: 50,
    rating: 4.9,
    badCount: 1,
    image: '/images/products/jc-ke-26/hero-studio-pair.jpg',
    gallery: [
      '/images/products/jc-ke-26/hero-studio-pair.jpg',
      '/images/products/jc-ke-26/detail-satin-pair.jpg',
      '/images/products/jc-ke-26/model-worn-profile.jpg',
      '/images/products/jc-ke-26/detail-hands-held.jpg',
      '/images/products/jc-ke-26/macro-wishbone-detail.jpg',
    ],
  },
  {
    id: 51,
    name: 'JC-KE-4',
    sku: 'JC-KE-4',
    slug: 'jc-ke-4',
    genre: 'EARRINGS',
    price: 849,
    originalPrice: 1799,
    reviewCount: 39,
    rating: 4.9,
    badCount: 1,
    image: '/images/products/jc-ke-4/hero-studio-pair.jpg',
    gallery: [
      '/images/products/jc-ke-4/hero-studio-pair.jpg',
      '/images/products/jc-ke-4/model-worn-portrait.jpg',
      '/images/products/jc-ke-4/macro-rose-detail.jpg',
    ],
  },
  {
    id: 50,
    name: 'JC-KE-23',
    sku: 'JC-KE-23',
    slug: 'jc-ke-23',
    genre: 'EARRINGS',
    price: 849,
    originalPrice: 1799,
    reviewCount: 44,
    rating: 4.9,
    badCount: 1,
    image: '/images/products/jc-ke-23/hero-satin-pair.jpg',
    gallery: [
      '/images/products/jc-ke-23/hero-satin-pair.jpg',
      '/images/products/jc-ke-23/model-worn-profile.jpg',
      '/images/products/jc-ke-23/detail-hands-held.jpg',
      '/images/products/jc-ke-23/macro-galaxy-detail.jpg',
    ],
  },
  {
    id: 49,
    name: 'JC-KE-9',
    sku: 'JC-KE-9',
    slug: 'jc-ke-9',
    genre: 'EARRINGS',
    price: 849,
    originalPrice: 1799,
    reviewCount: 46,
    rating: 4.9,
    badCount: 1,
    image: '/images/products/jc-ke-9/hero-beige-pair.jpg',
    gallery: [
      '/images/products/jc-ke-9/hero-beige-pair.jpg',
      '/images/products/jc-ke-9/detail-satin-pair.jpg',
      '/images/products/jc-ke-9/model-worn-profile.jpg',
      '/images/products/jc-ke-9/detail-hands-cupped.jpg',
      '/images/products/jc-ke-9/macro-wreath-detail.jpg',
    ],
  },\n`;

// Match {\r?\n\s+id: 48,\r?\n\s+name: 'JC-KE-7',
const targetRegex = /(\{\r?\n\s+id: 48,\r?\n\s+name: 'JC-KE-7',)/;
if (targetRegex.test(content)) {
  content = content.replace(targetRegex, rawProductsInsert + '$1');
  fs.writeFileSync(filePath, content, 'utf8');
  console.log('✓ Successfully inserted RAW_PRODUCTS 49-60!');
} else {
  console.error('Regex did not match!');
}
